import { config } from "dotenv";
import path from "node:path";
import fs from "node:fs";

// Load .env.local explicitly (for local scripts run via tsx/node)
config({ path: path.resolve(process.cwd(), ".env.local") });

import { createClient } from "@supabase/supabase-js";

// ─── Types ─────────────────────────────────────────────────────────────────

type ApiSportsResponse<T> = {
  response: T[];
  errors?: Record<string, string> | string[];
};

type ApiSquadPlayer = {
  id: number;
  name: string;
  age: number;
  number: number | null;
  position: string; // "Goalkeeper" | "Defender" | "Midfielder" | "Attacker"
  photo: string;
};

type ApiSquadEntry = {
  team: { id: number; name: string; logo: string };
  players: ApiSquadPlayer[];
};

type PlayerPosition = "GK" | "DEF" | "MID" | "FWD";

interface Player {
  name: string;
  team: string;
  position: PlayerPosition;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function parseArgs(argv: string[]) {
  const set = new Set(argv.slice(2));
  return {
    dryRun: set.has("--dry-run"),
    skipSanity: set.has("--skip-sanity"),
  };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function apiGet<T>(
  url: string,
  apiKey: string,
): Promise<{ data: T; ratelimitRemaining: number | null }> {
  const res = await fetch(url, {
    headers: { "x-apisports-key": apiKey },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`API request failed ${res.status}: ${text.slice(0, 500)}`);
  }
  const remainingHeader = res.headers.get("x-ratelimit-remaining");
  const remaining = remainingHeader != null ? Number(remainingHeader) : null;
  const json = (await res.json()) as T;
  return {
    data: json,
    ratelimitRemaining: Number.isFinite(remaining) ? remaining : null,
  };
}

function mapPosition(apiPosition: string): PlayerPosition | null {
  switch (apiPosition) {
    case "Goalkeeper":
      return "GK";
    case "Defender":
      return "DEF";
    case "Midfielder":
      return "MID";
    case "Attacker":
      return "FWD";
    default:
      return null;
  }
}

function escapeTs(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function renderPlayerArray(name: string, arr: Player[]): string {
  if (arr.length === 0) return `export const ${name}: Player[] = [];\n`;

  const lines: string[] = [`export const ${name}: Player[] = [`];
  let lastTeam = "";
  for (const p of arr) {
    if (p.team !== lastTeam) {
      if (lastTeam !== "") lines.push("");
      lines.push(`  // ${p.team}`);
      lastTeam = p.team;
    }
    lines.push(
      `  { name: "${escapeTs(p.name)}", team: "${escapeTs(p.team)}", position: "${p.position}" },`,
    );
  }
  lines.push(`];\n`);
  return lines.join("\n");
}

function generateFileContent(players: Player[], goalkeepers: Player[]): string {
  const now = new Date().toISOString();
  return [
    `// Auto-generated by scripts/update-player-data.ts — DO NOT EDIT MANUALLY`,
    `// Updated: ${now}`,
    ``,
    `export interface Player {`,
    `  name: string;`,
    `  team: string;`,
    `  position: "GK" | "DEF" | "MID" | "FWD";`,
    `}`,
    ``,
    renderPlayerArray("players", players),
    renderPlayerArray("goalkeepers", goalkeepers),
  ].join("\n");
}

// ─── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv);

  const apiKey = (process.env.API_FOOTBALL_KEY ?? "").trim();
  if (!apiKey) throw new Error("Missing API_FOOTBALL_KEY (set in .env.local or environment).");

  const supabaseUrl = (
    process.env.SUPABASE_URL ??
    process.env.NEXT_PUBLIC_SUPABASE_URL ??
    ""
  ).trim();
  const serviceKey = (process.env.SUPABASE_SERVICE_ROLE_KEY ?? "").trim();
  if (!supabaseUrl || !serviceKey) {
    console.error(
      "Missing NEXT_PUBLIC_SUPABASE_URL (or SUPABASE_URL) or SUPABASE_SERVICE_ROLE_KEY in .env.local",
    );
    process.exit(1);
  }

  const supabase = createClient(supabaseUrl, serviceKey, {
    auth: { persistSession: false },
  });

  // Read all team mappings (api_team_id → Predibol team name)
  console.log("Reading api_football_teams from Supabase…");
  const { data: teamRows, error: teamErr } = await supabase
    .from("api_football_teams")
    .select("api_team_id, team_name")
    .order("team_name", { ascending: true });

  if (teamErr) {
    throw new Error(`Failed to read api_football_teams: ${teamErr.message}`);
  }
  if (!teamRows || teamRows.length === 0) {
    throw new Error(
      "api_football_teams is empty. Run `npm run seed:api-football` first to populate team mappings.",
    );
  }
  console.log(`Found ${teamRows.length} teams in api_football_teams.`);

  const BASE_URL = "https://v3.football.api-sports.io";

  const outfieldPlayers: Player[] = [];
  const goalkeepers: Player[] = [];
  const teamsWithNoPlayers: string[] = [];

  for (let i = 0; i < teamRows.length; i++) {
    const row = teamRows[i]!;
    const { api_team_id: teamId, team_name: teamName } = row;

    process.stdout.write(
      `[${String(i + 1).padStart(2)}/${teamRows.length}] Fetching squad: ${teamName} (id=${teamId})… `,
    );

    try {
      const url = `${BASE_URL}/players/squads?team=${teamId}`;
      const { data, ratelimitRemaining } = await apiGet<
        ApiSportsResponse<ApiSquadEntry>
      >(url, apiKey);

      const entries = data.response ?? [];
      const squadEntry = entries[0];
      const squadPlayers = squadEntry?.players ?? [];

      if (squadPlayers.length === 0) {
        console.log(`⚠  0 players returned`);
        teamsWithNoPlayers.push(teamName);
      } else {
        let fwdMidCount = 0;
        let gkCount = 0;

        for (const p of squadPlayers) {
          const pos = mapPosition(p.position);
          if (!pos) {
            console.warn(`\n  Unknown position "${p.position}" for ${p.name} (${teamName}), skipping.`);
            continue;
          }
          const player: Player = { name: p.name, team: teamName, position: pos };
          if (pos === "GK") {
            goalkeepers.push(player);
            gkCount++;
          } else if (pos === "FWD" || pos === "MID") {
            outfieldPlayers.push(player);
            fwdMidCount++;
          }
          // DEF excluded from both arrays
        }

        const ratePart =
          ratelimitRemaining != null ? ` (rate remaining: ${ratelimitRemaining})` : "";
        console.log(`✓  ${squadPlayers.length} players (${fwdMidCount} FWD/MID, ${gkCount} GK)${ratePart}`);
      }
    } catch (err) {
      console.log(`✗  Error: ${String(err)}`);
      teamsWithNoPlayers.push(teamName);
    }

    // Rate-limit buffer between requests (skip after last)
    if (i < teamRows.length - 1) {
      await sleep(350);
    }
  }

  // Sort both arrays: by team name, then by player name within each team
  function sortPlayers(arr: Player[]): Player[] {
    return [...arr].sort((a, b) => {
      const teamCmp = a.team.localeCompare(b.team, "en");
      if (teamCmp !== 0) return teamCmp;
      return a.name.localeCompare(b.name, "en");
    });
  }

  const sortedPlayers = sortPlayers(outfieldPlayers);
  const sortedGoalkeepers = sortPlayers(goalkeepers);

  console.log(`\nSummary:`);
  console.log(`  FWD/MID (players):  ${sortedPlayers.length}`);
  console.log(`  GK (goalkeepers):   ${sortedGoalkeepers.length}`);
  if (teamsWithNoPlayers.length > 0) {
    console.log(`  Teams with no data: ${teamsWithNoPlayers.join(", ")}`);
  }

  // Sanity check: expect at least ~200 outfield players and ~96 goalkeepers (2 per team minimum)
  const SANITY_OUTFIELD = 200;
  const SANITY_GK = 96;
  const sanityFailed =
    sortedPlayers.length < SANITY_OUTFIELD || sortedGoalkeepers.length < SANITY_GK;

  if (sanityFailed && !args.skipSanity) {
    console.error(
      `\nSanity check failed: expected ≥${SANITY_OUTFIELD} outfield players and ≥${SANITY_GK} goalkeepers.`,
    );
    console.error(
      `Got ${sortedPlayers.length} outfield and ${sortedGoalkeepers.length} GK.`,
    );
    console.error(
      `The API may not have squad data yet for all teams. ` +
        `Re-run with --skip-sanity to force-write the file anyway.`,
    );
    process.exit(1);
  }

  const fileContent = generateFileContent(sortedPlayers, sortedGoalkeepers);

  if (args.dryRun) {
    console.log("\n--dry-run: output below (not written to disk):\n");
    console.log(fileContent);
    return;
  }

  const outPath = path.resolve(process.cwd(), "lib", "player-data.ts");
  fs.writeFileSync(outPath, fileContent, "utf-8");
  console.log(`\nWrote ${outPath}`);
  console.log(`Done.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
